name: gpe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2.0
  - matplotlib
  - openai
  - pip:
    - aq-llm-pivot==0.1.0
    - python-dotenv
    - requests-cache
    - beautifulsoup4
    - arxiv
    - wikipedia-api
    - praw
    - ddgs
    - newspaper4k
