name: gpe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2.0
  - matplotlib
  - openai
  - pip:
    - llm-pivot @ git+https://github.com/Aquarids/llm-pivot.git@v0.0.9
    - python-dotenv
    - requests-cache
    - beautifulsoup4
    - arxiv
    - wikipedia-api
    - praw
    - ddgs
    - newspaper4k
